version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "myCloudFormationStack2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xf3wsiug6nev"
s3_prefix = "myCloudFormationStack2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=467944476726.dkr.ecr.us-east-1.amazonaws.com/mycloudformationstack3ede8fe3/helloworldfunction19d43fc4repo"]
